### ISSUE TITLE
Where should I enter the order data in the database?

### ISSUE THREAD

**Issue by palanganero** [sergiq/redsys#2]
where I must enter the data in the database, in "Ds_Merchant_MerchantURL"
or in "Ds_Merchant_UrlOK"?

**Comment by sergiq** [comment]
After obtain all the information from RedSYS, you can store the information as you want. Ds_Merchant_MerchantURL and Ds_Merchant_UrlOK are two different concepts.

The first one is the URL used by RedSYS to send the feedback of the transaction (payment approved or rejected). It's a direct and async ommunication between RedSYS and your system (the user does not see anything).

The second one is the URL you want your user is redirected after a success payment.

**Comment by palanganero** [comment]
and can i use this code for check if the payment was successfull?
`<html> 
<body> 
<?php

	include 'apiRedsys.php';

	// Se crea Objeto
	$miObj = new RedsysAPI;


if (!empty( $_POST ) ) {//URL DE RESP. ONLINE
					
					$version = $_POST["Ds_SignatureVersion"];
					$datos = $_POST["Ds_MerchantParameters"];
					$signatureRecibida = $_POST["Ds_Signature"];
					

					$decodec = $miObj->decodeMerchantParameters($datos);	
					$kc = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7'; //Clave recuperada de CANALES
					$firma = $miObj->createMerchantSignatureNotif($kc,$datos);	

					echo PHP_VERSION."<br/>";
					echo $firma."<br/>";
					echo $signatureRecibida."<br/>";
					if ($firma === $signatureRecibida){
						echo "FIRMA OK";
					} else {
						echo "FIRMA KO";
					}
	}
	else{
		if (!empty( $_GET ) ) {//URL DE RESP. ONLINE
				
			$version = $_GET["Ds_SignatureVersion"];
			$datos = $_GET["Ds_MerchantParameters"];
			$signatureRecibida = $_GET["Ds_Signature"];
				
		
			$decodec = $miObj->decodeMerchantParameters($datos);
			$kc = 'sq7HjrUOBfKmC576ILgskD5srU870gJ7'; //Clave recuperada de CANALES
			$firma = $miObj->createMerchantSignatureNotif($kc,$datos);
		
			if ($firma === $signatureRecibida){
				echo "FIRMA OK";
			} else {
				echo "FIRMA KO";
			}
		}
		else{
			die("No se recibió respuesta");
		}
	}

?>
</body> 
</html> `
